{% set name = "pytest-ast-back-to-python" %}
{% set version = "1.2.1" %}
{% set hash = "1e594728637d0d03f639b91dc6afdb03f90dd8ccf783ec714545f18d0e9232dc" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0]}}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pytest >=3.0.0

test:
  imports:
    - pytest  # must be imported first because of circular imports in pytest_ast_back_to_python
    - pytest_ast_back_to_python

about:
  home: https://github.com/tomviner/pytest-ast-back-to-python
  license: BSD-3
  license_family: BSD
  summary: 'A plugin for pytest devs to view how assertion rewriting recodes the AST'
  dev_url: https://github.com/tomviner/pytest-ast-back-to-python

extra:
  recipe-maintainers:
    - nicoddemus
    - tomviner
