travis:
  secure:
    BINSTAR_TOKEN: QBNEb3YmzE/08ji5clx7TrNPTwW0WG/UWA90bUmYQMdFJeZQAM4HZL39K5C0w1hG59y+nMAFkTBLg7XAPkQ76ZMURw4RwfdAvxUgYo5o6f2FwHXU4BKX1h42apdWo3Qx4D7QOJI+8RLtIg/pUjaZKbf4WKNMECXR+T55a5Ji0w5SYwRcdAMD/8l4DFNU9nz35PTzU/br7A1kQq6FMiTpww4bqT21NbYSnORGJvM1cl+qZD7yASCsNB6sUwAr71SSjqo8W1eS47q/KOWRKb4rfPiPwtsRU8YYXO8wvwVqEIGtemnuxqObeozKuPsiUO0+XaOwrxYB9PpBR+ohP6A30WbuSrgQC7HCuxJ4KYinKYwca6l76TZFAMpPu+AvrUvJcV14VrzwBeHL8n92Oqo4sx1ZjDc9NC33jPFNGSgwdQQ86Jm3OIgJK+M/YR0stOH4yLHpu5w1bWEDI6+Yn201I/HaWJnEwD3SUE06FNGur5DR4hUMvhLIm8hWAO8Br688Eq6knK7NrRLzLmOE8mfv6At+BKhNIA5kVIb+V01kc4/nYw8kNUrYBWYo4lWvt2Cxt7hRtVxg/lFdxvzl2XNdvO832M6K1A0vYm/hNgei1w2pmwZoN0P96EMyF9aljJPiHyCym2FngqiDT+P3hPfB5qn6RrI0Q+TsLmmya9kipq0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
