travis:
  secure:
    BINSTAR_TOKEN: gX2aH0UspbdwFDARdIbjktarQifXEui11ed4NsAGpUP+9brmWJXooXFKtLydq/M9UjgfgvfX5UxFNwjAAYF8b2EBHNHA43gtvrmBJAK6Xc5z1wjJtPPjLftpcP5YUirTY3HvrOTsyJTIMvqdjoeT1w82W5ZEcgLrb8EV8qkOCqac6KwObVxTKtXjNpywQfvnMCz0f/4Z51wWLADsavymXUyp3/tdy/Cog5FbeNN3xwJQWCIJWD4MGl6rPLu4vlTzhyfa7sH6wrAiwsRSfVywHjLZvSyn9xb+Ly7+1PpLBfKcnmZSCClRS4h7bTkbwPfj7+EKQFzIWnWCMIO+zTqypPiXVFT/vbuilHZmM1jse3btH7b28IcQyjxuVvyo2myCgq84oRhDdEhkNZMuQkQOAP1QKxRCksYWgVbnSoZAnqeCJJDiwIqChB+6NnGyWptMAas1d4sI5Y4qcbUw9iyk9+8wXkD6waebqlU6Y6rzGvwjQG9pXzpncN9TSEQCVS3MAolmb5Uzb0twVrz8ad+tGzVA7aaSwAdVcJQ7nxxznDYGdBuYIk3ePl/ZhyG26Am0x8WbVUrxH7d3EwL9X6FdjqFKsLC3SHeIC53fCiQueO0fzDbj2H2w+jg3rf4gFcrI6c2cvKq2TA7voHnDVKACI9C61r1wzUgVbLKaPraRPJ8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
